### PR TITLE
introduce pep8 tests and unit test mechanisms

### PR DESCRIPTION
**Pull request by 4383**
Hi

# Overview
- Removing pep8 errors.
- Introduce tox and dev dependencies.
- Introduce automated code linting during travis workflow.

Cheers!

### CODE REVIEW

**Comment by 4383** [comment]
Hi @sergey-surkov don't forget to bind travis with this project to activate these features.
It's allow to automate a lot of thinks :)
I choose travis but if you have preferences we can use another service.

Automatic deployment is only allowed on git tags pushing on github you can continue to work on master without any risks to deploy on pypi by accident.

**Comment by sergey48k** [comment]
Hi @4383 

Thank you! Please give me a couple of days to review and look into travis.

**Comment by 4383** [comment]
Hi @sergey-surkov.

Yep sure take your time

**Comment by sergey48k** [comment]
Hi @4383 ,

I connected travis, and deployment work. Not sure why travis reports pypi upload failures on subsequent builds though. Maybe because nothing has changed? Also, note that the license badge seems broken. Do you know how to fix it?

**Comment by 4383** [comment]
Hi @sergey-surkov 
Greate news! 

Pypi can fail on deployment (github tag webhook event) because deployment try to deploy on every python version (2.7, 3.5, etc...) and pypi only permit one package by version, travis need to add an branch/tag option on deployment for avoid this behavior...

Can you giving to me the travis links for investigation?

Also I take a look for the license badge.

**Comment by 4383** [comment]
@sergey-surkov I went to add another check based on [bandit](https://pypi.org/project/bandit/).

Bandit is a tool designed to find common security issues in Python code. To do this Bandit processes each file, builds an [AST](https://docs.python.org/3.5/library/ast.html) from it, and runs appropriate plugins against the AST nodes.

These changes was amended to my previous commit :)

Also the CI seem to work perfectly.

**Comment by 4383** [comment]
Also I went to fix the license badge error, it's due to a misconfiguration typo on `setup.cfg`.

When this pull request will be merged I want to add more checks from [pyroma](https://pypi.org/project/pyroma/) to avoid misconfiguration error on packaging

**Comment by 4383** [comment]
The license badge will be fixed when you will deploy a new version on pypi (depend on the anishot python meta package informations available on pypi, so you need to deploy a newer version (`0.1.1`) on pypi to fix it).

Cheers!

**Pull request merged**
